### ISSUE TITLE
硬件平台

### ISSUE THREAD

**Issue by ianhom** [hdp7891000/Linux-driver-and-app#2]
我们需要先确定硬件平台，目前开发成员均拥有的板子是周立功的i.mx280A，该平台硬件资源如下:   

| 项目 | 参数 |
| --- | --- |
| CPU制造商 | Freescale |
| CPU型号 | i.mx280 |
| 位宽 | 32 |
| 核数 | 1 |
| 主频 | 454MHz |
| 内核 | ARM ARM9 |
| RAM | 64M |
| ROM | 128M NAND |

可作为选项之一。  
同时再看看其他板子是否合适。

**Comment by hdp7891000** [comment]
# 对比

## 此版子的优势

成员都有

## 此版子的劣势

不够现代

**那么要如何选择？**

_那么要如何选择？_

> 那么要如何选择？
- `那么要如何选择？`

**Comment by ianhom** [comment]
# 怎么定义“够现代”的板子

**Comment by hdp7891000** [comment]
_**ARM9核心相对古老了，比如A9的就比较现代**_

**Comment by ianhom** [comment]
核心的差异在简单应用上体现不是很出来，比如树莓派ZERO用的就是ARM11，而树莓派3则用的是A53架构，他们可以运行完全一样的系统镜像（系统卡直接插上就能用），拥有相同好玩的资源，好多新潮的应用。比如板子支持python会不会更“现代”一些

**Comment by hdp7891000** [comment]
树莓派的有源码吗？

**Comment by ianhom** [comment]
没见过，树莓派的底层不是很好搞，芯片也不是很主流

**Comment by ianhom** [comment]
How about NanoPi NEO?

|  | i.mx280A | NanoPi NEO |
| --- | --- | --- |
| CPU制造商 | Freescale | Allwinner |
| CPU型号 | i.mx280 | H3 |
| 位宽 | 32 | 32 |
| 核数 | 1 | **4** |
| 主频 | 454MHz | **1.2GHz** |
| 内核 | ARM ARM9 | **ARM Cortex-A7** |
| RAM | 64M | **512M** |
| ROM | 128M NAND | **8G TF card** |

性能强大，有足够的资源，有源码，能跑完整linux，带本地GCC，完整的网络环境，能玩python等新鲜应用，后续可继续深入学习。
最重要的是，**这个板子大家都有**

**Comment by jiaoweiming215** [comment]
> `**_给大家点个赞，向大神学习_**`

**Comment by ianhom** [comment]
@jiaoweiming215 
欢迎biang总莅临指导 :tada:

**Comment by hdp7891000** [comment]
那就用这个板子吧，谢谢大神提供支持。

**Comment by ianhom** [comment]
是感谢大家的支持，陪我任性:smile:
